# Generated by Django 3.0.3 on 2020-03-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200318_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.Category'),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
