# Generated by Django 3.0.3 on 2020-03-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200319_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclubuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='myclubuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='username',
        ),
    ]
