# Generated by Django 3.0.3 on 2020-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200319_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
