# Generated by Django 3.0.3 on 2020-03-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
